vegetables = {
    "Carrot": {"price": 1.99, "quantity": 10},
    "Broccoli": {"price": 2.49, "quantity": 10},
    "Spinach": {"price": 1.79, "quantity": 10},
    "Lettuce": {"price": 1.29, "quantity": 10},
    "Tomato": {"price": 2.99, "quantity": 10},
    "Cabbage": {"price": 1.59, "quantity": 10},
    "Pepper": {"price": 1.69, "quantity": 10},
    "Cucumber": {"price": 1.49, "quantity": 10},
    "Zucchini": {"price": 1.89, "quantity": 10},
    "Onion": {"price": 0.99, "quantity": 10},
    "Potato": {"price": 0.79, "quantity": 10},
    "Radish": {"price": 1.19, "quantity": 10},
    "Beet": {"price": 1.39, "quantity": 10},
    "Eggplant": {"price": 2.29, "quantity": 10},
    "Cauliflower": {"price": 2.09, "quantity": 10},
    "Pumpkin": {"price": 1.69, "quantity": 10},
    "Sweet Potato": {"price": 1.89, "quantity": 10},
    "Kale": {"price": 2.39, "quantity": 10},
    "Brussels Sprouts": {"price": 2.99, "quantity": 10},
    "Artichoke": {"price": 2.79, "quantity": 10},
    "Asparagus": {"price": 3.29, "quantity": 10},
    "Celery": {"price": 1.59, "quantity": 10},
    "Mushroom": {"price": 2.19, "quantity": 10},
    "Green Bean": {"price": 1.99, "quantity": 10},
    "Pea": {"price": 2.09, "quantity": 10},
    "Okra": {"price": 2.49, "quantity": 10},
    "Corn": {"price": 0.99, "quantity": 10},
    "Garlic": {"price": 0.79, "quantity": 10},
    "Ginger": {"price": 1.29, "quantity": 10},
    "Scallion": {"price": 1.19, "quantity": 10},
    "Leek": {"price": 1.69, "quantity": 10},
    "Chard": {"price": 2.09, "quantity": 10},
    "Romaine": {"price": 1.89, "quantity": 10},
    "Arugula": {"price": 2.29, "quantity": 10},
    "Endive": {"price": 2.39, "quantity": 10},
    "Fennel": {"price": 2.79, "quantity": 10},
    "Turnip": {"price": 0.99, "quantity": 10},
    "Rutabaga": {"price": 1.29, "quantity": 10},
    "Bok Choy": {"price": 1.39, "quantity": 10},
    "Kohlrabi": {"price": 1.59, "quantity": 10},
    "Squash": {"price": 2.19, "quantity": 10},
    "Parsnip": {"price": 2.49, "quantity": 10},
    "Collard Greens": {"price": 2.79, "quantity": 10},
    "Watercress": {"price": 1.99, "quantity": 10},
    "Mustard Greens": {"price": 1.89, "quantity": 10},
    "Broccoli Rabe": {"price": 1.69, "quantity": 10},
    "Dandelion Greens": {"price": 1.59, "quantity": 10},
    "Swiss Chard": {"price": 2.09, "quantity": 10},
    "Radish Greens": {"price": 2.39, "quantity": 10},
    "Beet Greens": {"price": 1.29, "quantity": 10},
    "Napa Cabbage": {"price": 1.19, "quantity": 10},
    "Cilantro": {"price": 1.99, "quantity": 10},
    "Parsley": {"price": 2.19, "quantity": 10},
    "Thyme": {"price": 2.49, "quantity": 10},
    "Rosemary": {"price": 2.79, "quantity": 10},
    "Basil": {"price": 1.69, "quantity": 10},
    "Oregano": {"price": 1.39, "quantity": 10},
    "Mint": {"price": 1.89, "quantity": 10},
    "Sage": {"price": 2.09, "quantity": 10},
    "Dill": {"price": 1.29, "quantity": 10},
    "Cumin": {"price": 1.19, "quantity": 10},
    "Coriander": {"price": 2.39, "quantity": 10},
    "Chives": {"price": 1.59, "quantity": 10},
    "Lemongrass": {"price": 1.99, "quantity": 10},
    "Tarragon": {"price": 1.89, "quantity": 10},
    "Marjoram": {"price": 2.09, "quantity": 10},
    "Lavender": {"price": 2.79, "quantity": 10},
    "Chervil": {"price": 1.29, "quantity": 10},
    "Bay Leaves": {"price": 1.19, "quantity": 10},
    "Lemon Balm": {"price": 2.29, "quantity": 10},
    "Chamomile": {"price": 1.39, "quantity": 10},
    "Parsley Root": {"price": 2.49, "quantity": 10},
    "Borage": {"price": 2.39, "quantity": 10},
    "Lovage": {"price": 2.79, "quantity": 10},
    "Epazote": {"price": 1.99, "quantity": 10},
    "Summer Squash": {"price": 1.19, "quantity": 10},
    "Winter Squash": {"price": 2.99, "quantity": 10}
}
